project:
  name: account
  author: wxj

db:
  dataSource:
    url: jdbc:mysql://127.0.0.1:3306/ap_account?useUnicode=true&characterEncoding=utf8
    user: root
    password: root
  table:
    prefix:
      - t_
      - tf_
      - tc_
      - tb_
      - ti_
    name:
    # 依次为：表名,业务主键字段(如果也是表主键就不用)
#      - t_account_title
      - t_inner_account
#      - t_outer_account
#      - t_outer_account_type
#      - t_outer_sub_account
#      - t_account_transaction
#      - t_outer_account_detail
#      - t_outer_sub_account_detail
#      - t_inner_account_detail
#      - t_buffered_detail
#      - t_buffered_rule
