project:
  name: payment
  author: wxj

db:
  dataSource:
    url: jdbc:mysql://127.0.0.1:3306/ap_payment?useUnicode=true&characterEncoding=utf8
    user: root
    password: root
  table:
    prefix:
    # 表名前缀
      - tb_ #支付业务表
      - t_
    name:
#      - tb_acquiring_order
#      - tb_withdraw_order
#      - tb_deposit_order
#      - t_pay_process
      - t_refund_process
#      - t_fund_detail
#      - t_flux_order
#      - t_flux_process