project:
  name: channel
  author: wxj

db:
  dataSource:
    url: jdbc:mysql://127.0.0.1:3306/ap_channel?useUnicode=true&characterEncoding=utf8
    user: root
    password: root
  table:
    prefix:
      - t_
      - tf_
      - tc_
      - tb_
      - ti_
    name:
    # 依次为：表名,业务主键字段(如果也是表主键就不用)
      - tb_biz_order
#      - tb_fund_in_order
#      - tb_refund_order
#      - ti_inst_order
#      - ti_inst_delay_order
#      - ti_inst_process_order
#      - tc_api_result_code
#      - tc_unity_result_code
#      - tc_fund_channel
#      - tc_api_request_no_mode
#      - tc_channel_api
#      - tc_channel_support_inst
      - tc_channel_maintain
#      - tc_fund_channel_limit
#      - tc_institution
#      - tc_pay_method
#      - tc_param_define
#      - tc_channel_param
#      - t_pay_order
#      - t_refund_order