spring:
  application:
    name: test-bank
  thymeleaf:
    prefix: classpath:/templates/   # 模板路径
    suffix: .html                  # 模板后缀
    cache: false                   # 是否缓存模板
  datasource:
    # 数据库访问配置, 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/ap_testbank?allowMultiQueries=true&serverTimezone=GMT%2B8&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    druid:
      initialSize: 1
      minIdle: 0
      maxActive: 10
      maxWait: 180000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 25200000
      validationQuery: select 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      filters: stat
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        reset-enable: true
        allow:
      web-stat-filter:
        enabled: true
        exclusions: /druid/*,*.js,*.gif,*.jpg,*.bmp,*.png,*.css,*.ico
        session-stat-enable: true
        session-stat-max-count: 1000
        url-pattern: /*
server:
  port: 8070