spring:
  application:
    name: test-bank-gateway
nacos:
  config:
    server-addr: 127.0.0.1:8848
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
    serialize-check-status: WARN
  protocol:
    name: tri
    port: -1
  registry:
    address: nacos://${nacos.config.server-addr}